const videos = [
  {
    id: 1,
    subject: "Python",
    topic: "Variables and Data Types",
    title: "Python Variables and Data Types in Telugu",
    channel: "Tech Telugu",
    duration: "12:30",
    language: "Telugu",
    difficulty: "Beginner",
    thumbnail: "https://placehold.co/600x340/667eea/ffffff?text=Python+Variables",
    youtubeUrl: "https://www.youtube.com/watch?v=kqtD5dpn9C8"
  },
  {
    id: 2,
    subject: "Python",
    topic: "Loops",
    title: "Python For and While Loops Explained",
    channel: "Programming with Mosh",
    duration: "15:45",
    language: "English",
    difficulty: "Beginner",
    thumbnail: "https://placehold.co/600x340/667eea/ffffff?text=Python+Loops",
    youtubeUrl: "https://www.youtube.com/watch?v=_uQrJ0TkZlc"
  },
  {
    id: 3,
    subject: "Python",
    topic: "Functions",
    title: "Python Functions Tutorial",
    channel: "CodeWithHarry",
    duration: "18:20",
    language: "Hindi",
    difficulty: "Intermediate",
    thumbnail: "https://placehold.co/600x340/667eea/ffffff?text=Python+Functions",
    youtubeUrl: "https://www.youtube.com/watch?v=qoSksQ4s_hg"
  },
  {
    id: 4,
    subject: "DBMS",
    topic: "Introduction to DBMS",
    title: "DBMS Basics for Beginners",
    channel: "Gate Smashers",
    duration: "14:10",
    language: "Telugu",
    difficulty: "Beginner",
    thumbnail: "https://placehold.co/600x340/764ba2/ffffff?text=DBMS+Basics",
    youtubeUrl: "https://www.youtube.com/watch?v=dl00fOOYLOM"
  },
  {
    id: 5,
    subject: "DBMS",
    topic: "SQL Queries",
    title: "SQL Tutorial for Beginners",
    channel: "Programming with Mosh",
    duration: "20:05",
    language: "English",
    difficulty: "Intermediate",
    thumbnail: "https://placehold.co/600x340/764ba2/ffffff?text=SQL+Queries",
    youtubeUrl: "https://www.youtube.com/watch?v=7S_tz1z_5bA"
  },
  {
    id: 6,
    subject: "DBMS",
    topic: "Normalization",
    title: "DBMS Normalization Explained",
    channel: "Gate Smashers",
    duration: "16:50",
    language: "Hindi",
    difficulty: "Advanced",
    thumbnail: "https://placehold.co/600x340/764ba2/ffffff?text=DBMS+Normalization",
  },
  {
    id: 7,
    subject: "Data Structures",
    topic: "Arrays",
    title: "Arrays in Data Structures",
    channel: "Apna College",
    duration: "13:40",
    language: "Telugu",
    difficulty: "Beginner",
    thumbnail: "https://placehold.co/600x340/ff6b6b/ffffff?text=Data+Structures+Arrays",
    youtubeUrl: "https://www.youtube.com/watch?v=0YbY8QO98e0"
  },
  {
    id: 8,
    subject: "Data Structures",
    topic: "Linked Lists",
    title: "Linked List Full Tutorial",
    channel: "freeCodeCamp.org",
    duration: "22:15",
    language: "English",
    difficulty: "Intermediate",
    thumbnail: "https://placehold.co/600x340/ff6b6b/ffffff?text=Linked+Lists",
    youtubeUrl: "https://www.youtube.com/watch?v=Hj_rA0dhr2I"
  },
  {
    id: 9,
    subject: "Data Structures",
    topic: "Stacks and Queues",
    title: "Stacks and Queues Explained",
    channel: "CodeWithHarry",
    duration: "19:30",
    language: "Hindi",
    difficulty: "Advanced",
    thumbnail: "https://placehold.co/600x340/ff6b6b/ffffff?text=Stacks+and+Queues",
    youtubeUrl: "https://www.youtube.com/watch?v=wjI1WNcIntg"
  }
];